[package]

name = "venv"
version = "0.5.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.16", features = ["derive"] }
clap_complete_command = "0.6.1"
crossterm = "0.28.0"
home = "0.5.5"

